### ISSUE TITLE
Partially works in Zenoss Core 5

### ISSUE THREAD

**Issue by JayCeeJr** [zenoss/ZenPacks.zenoss.PostgreSQL#16]
Data sources work in zenoss 5 but components don't populate. i.e. you get the overall server stats, but the individual databases and tables that once appeared under device components is missing. I am having similar issues with other zenpacks.

**Comment by trelane** [comment]
Is this still the case?  Many Zenpacks had issues early in the 5.x lifecycle that don't exist now.

**Comment by JayCeeJr** [comment]
Doesn't appear to be an issue anymore.
